language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
  - "iojs"
notifications:
  email: false
cache:
  directories:
    - node_modules
script: npm run coverage
after_success:
  - npm run coveralls
  - mkdir recursive
  - npm install -g yo
  - npm link
  - cd recursive && yo at-angular --default
  - npm test
  - npm run build
